### ISSUE TITLE
BSOD:CRITICAL_STRUCTURE_CORRUPTION

### ISSUE THREAD

**Issue by Alexmalab** [xetzzy/Fortnite-External-Source#15]
HOW TO SOLVE BSOD:CRITICAL_STRUCTURE_CORRUPTION
HELLO EVERYONE
![image](https://github.com/xetzzy/Fortnite-External-Source/assets/144114239/ff66d804-dcba-42a2-a4df-32ad9a69d766)

**Comment by xetzzy** [comment]
maybe the pattern is wrong for your windows version

**Comment by Alexmalab** [comment]
how to find pattern of my own windows version? any tutorials?
