### ISSUE TITLE
works great, please add silent aim

### ISSUE THREAD

**Issue by nibb15** [xetzzy/Fortnite-External-Source#19]
works great, please add silent aim and it somehow gives me an input delay. Could it be the overlay?

**Comment by iChqnge** [comment]
> works great, please add silent aim and it somehow gives me an input delay. Could it be the overlay?

can you add me on discord pls i need help rq Reese#0613

**Comment by boyo3473** [comment]
> works great, please add silent aim and it somehow gives me an input delay. Could it be the overlay?

will it get me banned and if yes what spoofer should i use (please give link toa an open source spoofer)

**Comment by kaprivs** [comment]
> > works great, please add silent aim and it somehow gives me an input delay. Could it be the overlay?
> 
> will it get me banned and if yes what spoofer should i use (please give link toa an open source spoofer)

dm me on discord my user is band0.z got like 3 different spoofers
