### ISSUE TITLE
relative_location, 4 related errors

### ISSUE THREAD

**Issue by dssoftx** [xetzzy/Fortnite-External-Source#25]
Line 14, game.hpp
relative_location is not a member of cache
relative_location undeclared identifier

Line 199, game.hpp
relative_location is not a member of cache
relative_location undeclared identifier

**Comment by dssoftx** [comment]
Visual Studio 2022 with latest SDK and WDK. When compiling UM project with latest cpp version and v143 tools

**Comment by NotYmL** [comment]
i just added `inline Vector3 relative_location;` to cache

**Comment by dssoftx** [comment]
Yeah adding that in namespace cache in sdk.hpp solved the error.
