### ISSUE TITLE
DriverEntry referenced in function FxDriverEntryWork, 1 unresolved externals

### ISSUE THREAD

**Issue by dssoftx** [xetzzy/Fortnite-External-Source#26]
cant compile.

**Comment by NotYmL** [comment]
LOL

**Comment by dssoftx** [comment]
Did you add anything to compile the km project?

**Comment by Exotikcheatt** [comment]
> Did you add anything to compile the km project?

the signed driver.sys here so you can sc create YourDriverNameHere binpath="PathToYourDriverHere/YourDriverNameHere.sys/" type=kernel the driver without problem but the driver is detected so usless and the CR3 is outdated soo ESP LAG

driver download : https://www.mediafire.com/file/8l16er01tqvl342/km.sys

**Comment by dssoftx** [comment]
what did you change to be able to compile?

**Comment by dssoftx** [comment]
I set entry point as driver_entry instead of DriverEntry, that solved it.
